services:

  transactiondb:
    image: postgres
    container_name: transactiondb
    restart: always
    environment:
      POSTGRES_DB: "mps-transaction"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "user1234"
    ports:
      - "5435:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - transactiondb
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: user1234
    ports:
      - "8000:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  flyway-transaction:
    image: flyway/flyway
    command: -url=jdbc:postgresql://transactiondb:5432/mps-transaction -user=user -password=user1234 -connectRetries=60 migrate
    depends_on:
      - transactiondb
    volumes:
      - ./data/sql/transaction:/flyway/sql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

networks:
  default:
    name: local-network