server:
  port: 8030

spring:
  application:
    name: mps-report-generator
  datasource:
    url: jdbc:postgresql://localhost:5435/mps-transaction
    username: user
    password: user1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: Always
